In [ ]:
Introduction to 3rd Party libraries in python:
    
    1.Numpy
    2.Pandas
    3.Matplotlib
    4.Openpxyl

In [ ]:
Introduction to Numpy:
Definition:Numpy is majorly used to do the numerical computations.All sorts of mathematical calculations we can be able to achieve
    with numpy

In [ ]:
installation process of numpy:

In [1]:
!pip install numpy

In [ ]:
Updating Numpy:

In [2]:
!pip install numpy --upgrade

  Found existing installation: numpy 1.19.3
    Uninstalling numpy-1.19.3:
      Successfully uninstalled numpy-1.19.3


tables 3.5.1 requires mock>=2.0, which is not installed.


In [ ]:
Introduction to datatypes of Numpy:----->array
    
Ndarray:----> n dimensional

In [ ]:
array and list **

In [ ]:
what is the diff btw list and array?? if given both of the choices which one would u prefer and why??`

In [ ]:
Numpy:
Reasons:
    
    1.efficiency in processing
    2.occupies lesser storage
    3.better indexing functionality

In [3]:
import numpy as np  #np ---->alias name

In [ ]:
Req:Create an array from a regular python list

In [4]:
array_one=np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [6]:
type(array_one)

numpy.ndarray

In [9]:
numbers=[9,8,7,6,5]
array_two=np.array(numbers)

In [10]:
array_two

array([9, 8, 7, 6, 5])

In [ ]:
x,y =====>x will be representing rows and y will be representing coloumns

In [ ]:
Req: i want to create an array of zeros.

In [11]:
array_of_zeros=np.zeros((5,5))   #(x,y) ===>(5,5)
array_of_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
Req:i want to create an array of ones.

In [13]:
array_of_ones=np.ones((5,4))  #5 rows and 4 cols.
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#NOTE:INTERNALLY ARRAYS WILL BE CONSIDERED AS FLOAT DATATYPE.

In [ ]:
req: want to create an array without the decimals.

In [14]:
array_of_ones_int=np.ones((2,4),dtype=np.int16)   #int16,int32,int64

array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)