In [1]:
import numpy as np

In [4]:
array_of_floats=np.arange(0,5,0.2)

In [5]:
array_of_floats  #0.2 is step value and which is ofcourse exclusive

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [ ]:
Two_Dimensional_Arrays:

In [6]:
array_2D=np.array([(1,3,5),(2,4,6)])

In [7]:
array_2D

array([[1, 3, 5],
       [2, 4, 6]])

In [8]:
array_2D.shape    #(x,y)===>2Dmatrix #(x)==1Dmatrix  #(x,y,z)===>3Dmatrix

(2, 3)

In [ ]:
#that meand that is a 2D_array and it means two rows and three colomns

In [ ]:
Using reshape to create 'N' Dimensional arrays:

In [ ]:
Req: i want to create an array of 6 numbers.

In [10]:
x=np.arange(6)

In [11]:
x

array([0, 1, 2, 3, 4, 5])

In [13]:
x.shape  #1D array

(6,)

In [ ]:
Req:i want to reshape this into 2,3 matrix?

In [14]:
array_nd=np.arange(6).reshape(2,3)

In [15]:
array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
#NOTE:the multiplication of the numbers in the reshape parenthesis should give the number in the arange parenthesis

In [16]:
x=np.arange(12).reshape(1,3,5)  #here,it is an error cuz,the multiplied value of the numbers in reshape is not equal to the number in arange

ValueError: cannot reshape array of size 12 into shape (1,3,5)

In [17]:
x=np.arange(12).reshape(3,4)

In [18]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
x.shape   #2Dmatrix

(3, 4)

In [ ]:
Printing Arrays:

In [20]:
a=np.arange(8)

In [21]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
a.shape  #1D array

(8,)

In [ ]:
2D array:

In [23]:
b=np.arange(12).reshape(3,4)

In [24]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
b.shape

(3, 4)

In [ ]:
3D array

In [26]:
c=np.arange(24).reshape(2,3,4)

In [27]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
c.shape  #3D array

(2, 3, 4)

In [ ]:
Arthematic Operations in arrays:

In [29]:
a=np.array([10,10,10])

In [30]:
b=np.array([5,5,5])

In [31]:
a+b

array([15, 15, 15])

In [32]:
a-b

array([5, 5, 5])

In [33]:
a*b

array([50, 50, 50])

In [34]:
a/b

array([2., 2., 2.])

In [36]:
a%3

array([1, 1, 1], dtype=int32)

In [37]:
b%5

array([0, 0, 0], dtype=int32)

In [45]:
cc=np.array([0.2,3.5,6.5])
cc

array([0.2, 3.5, 6.5])