In [1]:
import numpy as np

In [ ]:
Req: I want to create an empty array

In [7]:
array_empty=np.empty((2,3))

In [8]:
array_empty

array([[6.03e-322, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [ ]:
Req: hoiw to create an identity matrix

In [6]:
array_identity=np.eye(3)
array_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
array_identity_5=np.eye(5)
array_identity_5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
Req: Iwant to create an array of first 20 natural numbers

In [ ]:
#we use arange

In [10]:
array_20_numbers=np.arange(21)

In [11]:
array_20_numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
Req:20 even numbers

In [12]:
array_20_even_num=np.arange(2,21,2)        #Last value exclusive

In [13]:
array_20_even_num

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
